version: '3.8'

services:
  api_production:
    build:
      context: .
      target: production
    container_name: '${APP_DOCKER_NAME:-app_production}'
    ports:
      - 3000:3000
  api_dev:
    build:
      context: .
      target: dev
    container_name: '${APP_DOCKER_NAME:-app_dev}'
    ports:
      - 8000:3000
    volumes:
      - ./:/app
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      - SERVICES=events,sqs,dynamodb
      - DEBUG=true
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
